baseURL: https://languages-in-floss.eu
languageCode: fr
defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
title: Langues et logiciels libres
theme: minimo
pagination:
  pagerSize: 5
preserveTaxonomyNames: true
enableRobotsTXT: true
pygmentsCodefences: true
enableEmoji: false
params:
  info:
    description: Partages et aventures
    title404: We can't find this page, wrong URL?
  assets:
    favicon: favicon.ico
    gopher: ''
  copyright:
    prefix: CC-BY SA 4.0
    holder: Languages in FLOSS
    startYear: '2020'
    suffix: ''
  settings:
    dateFormat: 2006-01-02
    listDateFormat: 2006-01-02
    archiveDateFormat: 01-02
    hideEntryNavigation:
    - page
    hideEntryMeta:
    - page
    showReadingTime: false
    showLastmod: true
    taxonomyCloudShuffle: false
    accentColor: '#ffcd00'
    hideMainMenu: false
  sidebar:
    enable: true
  widgets:
    header:
    - breadcrumbs
    homepage:
    - recent_posts
    sidebar:
    - about
    - languages
    - sidebar_menu
    - taxonomy_cloud
    - search
    footer:
    - social_menu
  seo:
    titleSeparator: •
  comments:
    enable: true
  social:
    email: contact@languages-in-floss.eu
    github: languages-in-floss
    mastodon: https://mamot.fr/@jibec
  search:
    client: fuse
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
permalinks:
  page: /:title/
  posts: /:year/:month/:title/
blackfriday:
  hrefTargetBlank: true
languages:
  ca:
    lang: ca
    contentDir: content-translated/ca
    languageName: Català (Catalan)
    title: Idiomes i programari lliure
    weight: 1
    params:
      lang: ca
      info:
        description: Accions i aventures
        title404: No podem trobar aquesta pàgina, URL incorrecte?
  es:
    lang: es
    contentDir: content-translated/es
    languageName: Español (Spannish)
    title: Lenguas y programas libres
    weight: 1
    params:
      lang: es
      info:
        description: Concomitancias y aventuras
        title404: No podemos encontrar esta página, ¿URL incorrecta?
  fi:
    lang: fi
    contentDir: content-translated/fi
    languageName: Suomi (Finnish)
    title: Kielet ja vapaat ohjelmistot
    weight: 1
    params:
      lang: fi
      info:
        description: Jakaminen ja seikkailut
        title404: Emme löydä tätä sivua, väärä URL-osoite?
  fr:
    lang: fr
    contentDir: content/fr
    languageName: Français (French)
    title: Langues et logiciels libres
    weight: 1
    params:
      lang: fr
      info:
        description: Partages et aventures
        title404: Nous ne trouvons pas cette page, URL incorrecte ?
  id:
    lang: id
    contentDir: content-translated/id
    languageName: Bahasa Indonesia (Indonesian)
    title: Bahasa dan perangkat lunak bebas
    weight: 1
    params:
      lang: id
      info:
        description: Berbagi dan petualangan
        title404: Kami tidak dapat menemukan halaman ini, apakah URL-nya salah?
  ko:
    lang: ko
    contentDir: content-translated/ko
    languageName: 한국어 (Korean)
    title: 언어 및 무료 소프트웨어
    weight: 1
    params:
      lang: ko
      info:
        description: 공유 및 모험
        title404: 이 페이지를 찾을 수 없습니다, URL이 잘못되었나요?
  pt_BR:
    lang: pt_BR
    contentDir: content-translated/pt_BR
    languageName: Português (Brazil)
    title: Idiomas e software livre
    weight: 1
    params:
      lang: pt_BR
      info:
        description: Desafios e aventuras
        title404: Não encontramos esta página, URL incorreta?
  uk:
    lang: uk
    contentDir: content-translated/uk
    languageName: Українська (Ukrainian)
    title: Вільні мови та логіка
    weight: 1
    params:
      lang: uk
      info:
        description: Спільне використання та пригоди
        title404: Ми не можемо знайти цю сторінку, невірна URL-адреса?
