title: Γλώσσες και ελεύθερο λογισμικό
languageName: Ελληνικά (Greek)
params:
  info:
    title404: Δεν ήταν δυνατή η εύρεση αυτής της σελίδας. Είναι σωστό το URL;
    description: Σκέψεις και εμπειρίες
